using System.Numerics;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Mobs;
using Content.Shared.ScavPrototype.Implants;
using Content.Shared._Shitmed.Targeting;
using Content.Shared._Shitmed.Medical.Surgery.Wounds;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.ScavPrototype.Implants.UI;

[GenerateTypedNameReferences]
public sealed partial class ScavImplantWindow : BaseWindow
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private EntityUid _spriteViewEntity;

    [ValidatePrototypeId<EntityPrototype>]
    private readonly EntProtoId _bodyView = "AlertSpriteView";

    private bool _isBleeding;
    private double _bleedFlashTimer;
    private readonly ECGGraph _ecgGraph;

    public ScavImplantWindow()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();

        // Load background and screen textures
        var rsiPath = new ResPath("/Textures/_ScavPrototype/Interface/Medimplant/medback.rsi");
        var specifier = new SpriteSpecifier.Rsi(rsiPath, "computerBack");
        BackgroundFrame.Texture = _spriteSystem.Frame0(specifier);

        var screenRsiPath = new ResPath("/Textures/_ScavPrototype/Interface/Medimplant/medimp.rsi");
        var screenSpecifier = new SpriteSpecifier.Rsi(screenRsiPath, "screenStatic");
        ScreenOverlay.Texture = _spriteSystem.Frame0(screenSpecifier);

        // === LAYOUT ===
        // screenStatic.png is 128x164 px, rendered at 2x = 256x328.
        // computerBack.png is 159x271 px, rendered at 2x = 318x542.
        // The monitor body extends from row 0..262 (1x), the screen area is inset.
        // ScreenContainer is positioned so that the screenStatic overlay aligns
        // perfectly with the CRT screen area of the computerBack sprite.

        BackgroundFrame.SetSize = new Vector2(318, 542);
        LayoutContainer.SetPosition(ScreenContainer, new Vector2(8, 22));
        ScreenContainer.SetSize = new Vector2(256, 328);

        // Bezel labels (in MainLayout, above the screen)
        LayoutContainer.SetPosition(ExperimentLabel, new Vector2(34, 4));
        LayoutContainer.SetPosition(StatsLabel, new Vector2(34, 18));

        // Close button in top-right bezel
        LayoutContainer.SetPosition(CloseButton, new Vector2(288, 8));
        CloseButton.SetSize = new Vector2(22, 22);
        CloseButton.OnPressed += _ => Close();

        // All coordinates below are in ScreenContainer space (0,0 = top-left of screen overlay).
        // Sprite pixel (px,py) -> screen coord (px*2, py*2).

        // --- Section 1: Above first dotted separator (y<48) ---
        // Brain health bar: no dedicated bar frame in the sprite at the top,
        // but there's empty space between the top border (y~30) and the first separator (y=48).
        // Place the health bar in the gap between the top decoration and the content icons.
        // The left decoration extends to about x=40 in screen coords at the top.
        // Place bar at screen y=36 (just below top border), spanning the width.
        LayoutContainer.SetPosition(BrainHealthBar, new Vector2(40, 36));
        BrainHealthBar.SetSize = new Vector2(176, 6);

        // Brain health text + Total health text: below the bar
        // Place at y=44, between bar and the next content row
        LayoutContainer.SetPosition(BrainHealthText, new Vector2(28, 44));
        LayoutContainer.SetPosition(TotalHealthText, new Vector2(80, 44));

        // --- Section 1 content: y=48..96 (between dotted seps at y=48 and y=96) ---
        // Left ruler icons are at screen x=8..26, so text starts after x=28.
        // Row 1 (y=52..68): Heart icons at x=24..26, body cross at x=146..160, radiation at x=214..226
        // Place blood text in the gap between left icons and body cross icon
        LayoutContainer.SetPosition(BleedingWarningIcon, new Vector2(28, 54));
        LayoutContainer.SetPosition(BloodText, new Vector2(46, 56));

        // Pain text: between body cross (ends x=160) and radiation icon (starts x=214)
        LayoutContainer.SetPosition(PainText, new Vector2(162, 56));

        // Temperature text: next to thermometer icon at top-right (screen x=208..220, y=42..46)
        // Place just below it or next to it
        LayoutContainer.SetPosition(TemperatureText, new Vector2(208, 48));

        // Row 2 (y=76..90): Second row of left icons, right rectangle frame
        // This area has the right panel sub-separator at y=72.
        // No specific values go here in our current design.

        // --- Section 2: y=96..188 (between dotted sep at y=96 and full sep at y=188) ---

        // Bar frame 1 (thirst): screen x=28..132, y=108..116 (inner y=110..114)
        LayoutContainer.SetPosition(ThirstBar, new Vector2(30, 110));
        ThirstBar.SetSize = new Vector2(100, 4);

        // Bar frame 2 (hunger): screen x=28..156, y=130..138 (inner y=132..136)
        LayoutContainer.SetPosition(HungerBar, new Vector2(30, 132));
        HungerBar.SetSize = new Vector2(124, 4);

        // Radiation text: DNA/bio icons at screen x=194..224, y=166..182
        // Place text next to/below those icons
        LayoutContainer.SetPosition(RadText, new Vector2(170, 170));

        // --- Section 3: y=188..260 (between full seps at y=188 and y=260) ---
        // Heart outline: screen x=16..66, y=196..234
        // Bar chart: screen x=178..224, y=196..230

        // Pulse text: next to heart outline, in the gap between heart and bar chart
        LayoutContainer.SetPosition(PulseText, new Vector2(68, 206));

        // ECG graph: in the wide empty space between heart and bar chart
        LayoutContainer.SetPosition(PulseGraphContainer, new Vector2(68, 218));
        PulseGraphContainer.SetSize = new Vector2(108, 30);

        // --- Section 4: y=260..328 (below last full separator at y=260) ---
        // Temp V icon at screen x=8..20, y=266..278
        // Speaker icon at screen x=178..218, y=266..278
        // Empty space for additional data or left blank

        // Doll sprite: place on the second physical monitor screen (below main screen)
        // The computerBack sprite shows a second screen area starting at roughly y=200 (1x) = y=400 (2x)
        // within the MainLayout. But since DollSpriteView is a child of ScreenContainer,
        // we need to place it relative to ScreenContainer.
        // The second screen in computerBack is at roughly y=200..254 (1x) = y=400..508 (2x) in MainLayout.
        // ScreenContainer is at MainLayout y=22, so relative to ScreenContainer: y=400-22=378 to y=508-22=486.
        // Center it: ~y=400, x centered at ~128 (half of 256)
        LayoutContainer.SetPosition(DollSpriteView, new Vector2(108, 390));
        DollSpriteView.SetSize = new Vector2(80, 80);

        // ECG graph control
        _ecgGraph = new ECGGraph();
        PulseGraphContainer.AddChild(_ecgGraph);

        // Apply flat styles to progress bars (transparent background, green foreground)
        var fgStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#18E298") };
        var bgStyle = new StyleBoxFlat { BackgroundColor = Color.Transparent };

        BrainHealthBar.ForegroundStyleBoxOverride = fgStyle;
        BrainHealthBar.BackgroundStyleBoxOverride = bgStyle;
        ThirstBar.ForegroundStyleBoxOverride = fgStyle;
        ThirstBar.BackgroundStyleBoxOverride = bgStyle;
        HungerBar.ForegroundStyleBoxOverride = fgStyle;
        HungerBar.BackgroundStyleBoxOverride = bgStyle;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Update ECG line animation
        _ecgGraph.UpdateTime(args.DeltaSeconds);

        // Flash bleeding warning icon if patient is bleeding
        if (_isBleeding)
        {
            _bleedFlashTimer += args.DeltaSeconds;
            if (_bleedFlashTimer >= 0.4)
            {
                _bleedFlashTimer = 0.0;
                BleedingWarningIcon.Visible = !BleedingWarningIcon.Visible;
            }
        }
        else
        {
            BleedingWarningIcon.Visible = false;
        }
    }

    public void UpdateState(ScavImplantUpdateMessage msg)
    {
        // 1. Header & stats
        ExperimentLabel.Text = $"{msg.SpeciesName.ToUpper()}";
        StatsLabel.Text = $"{msg.Height}cm | {msg.Age}y | #{msg.EntityName.GetHashCode() & 0xFFFF:X4}";

        // 2. Brain health
        BrainHealthBar.Value = (int)(msg.BrainHealth * 100f);
        BrainHealthText.Text = $"{(int)(msg.BrainHealth * 100f)}";

        // 3. Overall health percentage
        TotalHealthText.Text = $"{(int)msg.HealthPercent}%";

        // 4. Blood
        BloodText.Text = $"{msg.BloodAmount * 5.0f:F2}L | {(int)(msg.BloodAmount * 100f)}%";
        _isBleeding = msg.IsBleeding;

        // 5. Pain
        PainText.Text = $"{(int)msg.PainPercent}%";

        // 6. Temperature
        TemperatureText.Text = $"{msg.Temperature:F1}'c";

        // 7. Water & Food
        HungerBar.Value = (int)(msg.HungerPercent * 100f);
        ThirstBar.Value = (int)(msg.ThirstPercent * 100f);

        // 8. Radiation
        RadText.Text = $"{msg.Radiation:F1}gy";

        // 9. Pulse
        PulseText.Text = $"{msg.Pulse} bpm";
        _ecgGraph.UpdateBpm(msg.Pulse);

        // 10. Doll health
        var targetEntity = _entityManager.GetEntity(msg.TargetEntity);
        if (_entityManager.HasComponent<HumanoidAppearanceComponent>(targetEntity))
        {
            var dollIcon = SetupIcon(msg.BodyParts, msg.BleedingParts);
            if (dollIcon.HasValue)
            {
                DollSpriteView.SetEntity(dollIcon.Value);
                DollSpriteView.Visible = true;
            }
        }
        else
        {
            DollSpriteView.SetEntity(targetEntity);
            DollSpriteView.Visible = true;
        }
    }

    private EntityUid? SetupIcon(Dictionary<TargetBodyPart, WoundableSeverity>? body, Dictionary<TargetBodyPart, bool> bleeding)
    {
        if (body is null)
            return null;

        if (!_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);

        _spriteViewEntity = _entityManager.Spawn(_bodyView);

        if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return null;

        int layer = 0;
        foreach (var (bodyPart, integrity) in body)
        {
            string enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            int enumValue = (int) integrity;
            var baseRsiPath = new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi");
            var rsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_{enumValue}");
            CreateOrAddToLayer(sprite, rsi, layer);
            layer++;

            if (bleeding.TryGetValue(bodyPart, out var isBleeding) && isBleeding)
            {
                var bleedRsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_bleed");
                CreateOrAddToLayer(sprite, bleedRsi, layer);
                layer++;
            }
        }
        return _spriteViewEntity;
    }

    private void CreateOrAddToLayer(SpriteComponent sprite, SpriteSpecifier rsi, int layer)
    {
        if (!sprite.TryGetLayer(layer, out _))
            sprite.AddLayer(_spriteSystem.Frame0(rsi));
        else
            sprite.LayerSetTexture(layer, _spriteSystem.Frame0(rsi));

        sprite.LayerSetScale(layer, new Vector2(2f, 2f));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing && !_entityManager.Deleted(_spriteViewEntity))
        {
            _entityManager.QueueDeleteEntity(_spriteViewEntity);
        }
    }
}

/// <summary>
/// Custom Control that draws a realistic animated ECG heartbeat waveform.
/// Uses a proper PQRST complex with smooth transitions between waves.
/// The waveform scrolls left-to-right like a real cardiac monitor.
/// </summary>
public sealed class ECGGraph : Control
{
    private float _time;
    private int _bpm = 75;
    private float _accumulatedScroll;
    private readonly List<float> _history = new();

    // Glow effect: we draw the line multiple times with decreasing alpha and increasing width
    private static readonly Color LineColor = Color.FromHex("#18E298");
    private static readonly Color GlowColor = new(0.094f, 0.886f, 0.596f, 0.15f);

    public void UpdateBpm(int bpm)
    {
        _bpm = bpm;
    }

    public void UpdateTime(float delta)
    {
        var beatInterval = 60.0f / MathF.Max(1.0f, _bpm);

        // Scroll speed: 50 pixels per second (slower for a smooth medical monitor feel)
        var pixelsToScroll = delta * 50.0f;
        _accumulatedScroll += pixelsToScroll;
        var scrollCount = (int) _accumulatedScroll;
        _accumulatedScroll -= scrollCount;

        // Remove old points from the left
        if (scrollCount > 0)
        {
            if (_history.Count > 0)
            {
                if (scrollCount >= _history.Count)
                    _history.Clear();
                else
                    _history.RemoveRange(0, scrollCount);
            }
        }

        // Fill in new points on the right
        var bounds = PixelSizeBox;
        var targetCount = bounds.Width > 0 ? (int)bounds.Width : 108;

        while (_history.Count < targetCount)
        {
            _time += (1.0f / 50.0f); // matches scroll speed
            var t = _time % beatInterval;
            var normalized = t / beatInterval; // 0..1 within one beat cycle
            var yOffset = GetECGValue(normalized);
            _history.Add(yOffset);
        }
    }

    /// <summary>
    /// Attempt to produce a realistic PQRST ECG waveform.
    /// normalized = 0..1 representing one full cardiac cycle.
    /// Returns y-offset in pixels (positive = upward deflection).
    /// </summary>
    private static float GetECGValue(float normalized)
    {
        // A typical ECG cycle timing (as fraction of beat):
        //   P wave:   0.05 - 0.15   (atrial depolarization, small upward bump)
        //   PR seg:   0.15 - 0.20   (flat baseline)
        //   Q wave:   0.20 - 0.23   (small downward dip)
        //   R wave:   0.23 - 0.28   (large upward spike)
        //   S wave:   0.28 - 0.32   (downward dip below baseline)
        //   ST seg:   0.32 - 0.40   (return to baseline)
        //   T wave:   0.40 - 0.55   (repolarization, medium upward bump)
        //   Rest:     0.55 - 1.00   (flat baseline)

        float t = normalized;

        // P wave: gentle sine bump
        if (t >= 0.05f && t < 0.15f)
        {
            float phase = (t - 0.05f) / 0.10f;
            return 2.5f * MathF.Sin(phase * MathF.PI);
        }

        // Q wave: small downward notch
        if (t >= 0.20f && t < 0.23f)
        {
            float phase = (t - 0.20f) / 0.03f;
            return -2.0f * MathF.Sin(phase * MathF.PI);
        }

        // R wave: sharp upward spike
        if (t >= 0.23f && t < 0.28f)
        {
            float phase = (t - 0.23f) / 0.05f;
            return 12.0f * MathF.Sin(phase * MathF.PI);
        }

        // S wave: downward dip
        if (t >= 0.28f && t < 0.32f)
        {
            float phase = (t - 0.28f) / 0.04f;
            return -4.0f * MathF.Sin(phase * MathF.PI);
        }

        // T wave: medium upward bump
        if (t >= 0.40f && t < 0.55f)
        {
            float phase = (t - 0.40f) / 0.15f;
            return 4.0f * MathF.Sin(phase * MathF.PI);
        }

        // Baseline
        return 0.0f;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var bounds = PixelSizeBox;
        if (_history.Count < 2)
            return;

        var centerY = bounds.Height / 2f;

        // Draw a subtle glow layer first (thicker, more transparent)
        for (int x = 1; x < _history.Count && x < (int)bounds.Width; x++)
        {
            var p1 = new Vector2(x - 1, centerY - _history[x - 1]);
            var p2 = new Vector2(x, centerY - _history[x]);
            handle.DrawLine(p1, p2, GlowColor);
            // Offset lines for thickness
            handle.DrawLine(p1 + new Vector2(0, 1), p2 + new Vector2(0, 1), GlowColor);
            handle.DrawLine(p1 - new Vector2(0, 1), p2 - new Vector2(0, 1), GlowColor);
        }

        // Draw the main crisp line
        for (int x = 1; x < _history.Count && x < (int)bounds.Width; x++)
        {
            var p1 = new Vector2(x - 1, centerY - _history[x - 1]);
            var p2 = new Vector2(x, centerY - _history[x]);
            handle.DrawLine(p1, p2, LineColor);
        }
    }
}
